#Ignore items that are named, have lore or are enchanted
ignore_custom_items: true

text:
  back: "&cBack"
  back-lore: "&7Click to go to the next page"
  next: "&2Next Page"
  next-lore: "&7Click to go to the previous page"
  previous: "&cPrevious Page"
  previous-lore: "&7Click to go to the previous page"
  item-enabled: "&a%item%"
  item-disabled: "&c%item%"
  item-enabled-lore: "&a&lWILL &7be picked up"
  item-disabled-lore: "&c&lWILL NOT &7be picked up"
  item-lore: "&7when item filter is &nenabled."
  categories-title: "&7Categories"

categoriesGUI:
  rows: 1 #How many rows should the categories GUI have (1-6)
  categories:
    Mining:
      enabled: true
      size: 6 # Size in rows (1-6) (default 6)
      material: DIAMOND_PICKAXE
      name: "&6Mining"
      slot: 2
      title: Mining Item Filter
      items:
        - COAL_ORE
        - IRON_ORE
        - GOLD_ORE
        - REDSTONE_ORE
        - LAPIS_ORE
        - DIAMOND_ORE
        - EMERALD_ORE
        - GRAVEL
        - STONE
        - COAL
        - IRON_INGOT
        - GOLD_INGOT
        - REDSTONE
        - LAPIS_LAZULI
        - DIAMOND
        - EMERALD
        - FLINT
        - COBBLESTONE
        - COAL_BLOCK
        - IRON_BLOCK
        - GOLD_BLOCK
        - REDSTONE_BLOCK
        - LAPIS_BLOCK
        - DIAMOND_BLOCK
        - EMERALD_BLOCK
        - OBSIDIAN
        - DIRT
        - GRANITE
        - ANDESITE
        - DIORITE
        - SAND
        - SANDSTONE
    PvP:
      enabled: true
      material: DIAMOND_CHESTPLATE
      name: "&6Pvp"
      slot: 3
      title: Pvp Item Filter
      items:
        - IRON_HELMET
        - IRON_CHESTPLATE
        - IRON_LEGGINGS
        - IRON_BOOTS
        - IRON_SWORD
        - IRON_SHOVEL
        - IRON_PICKAXE
        - IRON_AXE
        - IRON_HOE
        - GOLDEN_HELMET
        - GOLDEN_CHESTPLATE
        - GOLDEN_LEGGINGS
        - GOLDEN_BOOTS
        - GOLDEN_SWORD
        - GOLDEN_SHOVEL
        - GOLDEN_PICKAXE
        - GOLDEN_AXE
        - GOLDEN_HOE
        - DIAMOND_HELMET
        - DIAMOND_CHESTPLATE
        - DIAMOND_LEGGINGS
        - DIAMOND_BOOTS
        - DIAMOND_SWORD
        - DIAMOND_SHOVEL
        - DIAMOND_PICKAXE
        - DIAMOND_AXE
        - DIAMOND_HOE
        - LEATHER_HELMET
        - LEATHER_CHESTPLATE
        - LEATHER_LEGGINGS
        - LEATHER_BOOTS
        - WOODEN_SWORD
        - WOODEN_SHOVEL
        - WOODEN_PICKAXE
        - WOODEN_AXE
        - WOODEN_HOE
        - TRIDENT
        - BOW
        - CROSSBOW
        - ARROW
        - SHIELD
        - ENCHANTED_GOLDEN_APPLE
        - GOLDEN_APPLE
        - COOKED_BEEF
        - MUSHROOM_STEW
    Herbalism:
      enabled: true
      material: DIAMOND_HOE
      name: "&6Herbalism"
      slot: 4
      title: Herbalism Item Filter
      items:
        - CARROT
        - POTATO
        - WHEAT_SEEDS
        - PUMPKIN_SEEDS
        - MELON_SEEDS
        - BEETROOT_SEEDS
        - RED_MUSHROOM
        - BROWN_MUSHROOM
        - BAMBOO
        - SWEET_BERRIES
        - POISONOUS_POTATO
        - WHEAT
        - PUMPKIN
        - MELON_SLICE
        - BEETROOT
        - CACTUS
        - VINE
        - GRASS
        - OAK_SAPLING
        - SPRUCE_SAPLING
        - HAY_BLOCK
        - BIRCH_SAPLING
        - JUNGLE_SAPLING
        - OAK_SAPLING
        - ACACIA_SAPLING
        - DARK_OAK_SAPLING
        - DANDELION
        - POPPY
        - BLUE_ORCHID
        - ALLIUM
        - AZURE_BLUET
        - RED_TULIP
        - ORANGE_TULIP
        - WHITE_TULIP
        - PINK_TULIP
        - OXEYE_DAISY
        - CORNFLOWER
        - LILY_OF_THE_VALLEY
        - SUNFLOWER
        - LILAC
        - ROSE_BUSH
        - PEONY
        - TALL_GRASS
        - WITHER_ROSE
        - LILY_PAD
    Drops:
      enabled: true
      material: BONE
      name: "&6Drops"
      slot: 6
      title: Drops Item Filter
      items:
        - BONE
        - ARROW
        - STRING
        - GUNPOWDER
        - ROTTEN_FLESH
        - ENDER_PEARL
        - BLAZE_ROD
        - GHAST_TEAR
        - GOLD_NUGGET
        - SPIDER_EYE
        - MAGMA_CREAM
        - PRISMARINE_SHARD
        - SLIME_BALL
        - LEATHER
        - BAMBOO
        - FEATHER
        - MUTTON
        - RABBIT
        - CHICKEN
        - PORKCHOP
        - SALMON
        - BEEF
        - COD
        - PUFFERFISH
        - INK_SAC
        - TROPICAL_FISH
        - IRON_INGOT
        - POPPY
        - SNOWBALL
        - PRISMARINE_CRYSTALS
        - EGG