#Ignore items that are named, have lore or are enchanted
ignore_custom_items: true

text:
  material-enabled: "&a%item% has been enabled!"
  material-disabled: "&c%item% has been disabled!"
  material-reset: "&6Item filter reset!"
  filter-enabled: "&6Item filter turned on!"
  filter-disabled: "&6Item filter turned off!"
  item-enabled: "&a%item%"
  item-disabled: "&c%item%"
  item-enabled-lore: "&a&lWILL &7be picked up"
  item-disabled-lore: "&c&lWILL NOT &7be picked up"
  item-lore: "&7when item filter is &nenabled."
  categories-title: "&7Categories"

categoriesGUI:
  rows: 1 #How many rows should the categories GUI have (1-6)
  categories:
    Mining:
      enabled: true
      size: 6 # Size in rows (1-6) (default 6)
      material: DIAMOND_PICKAXE
      name: "&6Mining"
      slot: 3
      title: Mining Item Filter
      items:
        - COAL_ORE
        - IRON_ORE
        - GOLD_ORE
        - REDSTONE_ORE
        - LAPIS_ORE
        - DIAMOND_ORE
        - EMERALD_ORE
        - GRAVEL
        - STONE
        - COAL
        - IRON_INGOT
        - GOLD_INGOT
        - REDSTONE
        - DIAMOND
        - EMERALD
        - FLINT
        - COBBLESTONE
        - COAL_BLOCK
        - IRON_BLOCK
        - GOLD_BLOCK
        - REDSTONE_BLOCK
        - LAPIS_BLOCK
        - DIAMOND_BLOCK
        - EMERALD_BLOCK
        - OBSIDIAN
        - DIRT
        - SAND
        - SANDSTONE
    PvP:
      enabled: true
      material: DIAMOND_CHESTPLATE
      name: "&6Pvp"
      slot: 4
      title: Pvp Item Filter
      items:
        - IRON_HELMET
        - IRON_CHESTPLATE
        - IRON_LEGGINGS
        - IRON_BOOTS
        - IRON_SWORD
        - IRON_SPADE
        - IRON_PICKAXE
        - IRON_AXE
        - IRON_HOE
        - GOLD_HELMET
        - GOLD_CHESTPLATE
        - GOLD_LEGGINGS
        - GOLD_BOOTS
        - GOLD_SWORD
        - GOLD_SPADE
        - GOLD_PICKAXE
        - GOLD_AXE
        - GOLD_HOE
        - DIAMOND_HELMET
        - DIAMOND_CHESTPLATE
        - DIAMOND_LEGGINGS
        - DIAMOND_BOOTS
        - DIAMOND_SWORD
        - DIAMOND_SPADE
        - DIAMOND_PICKAXE
        - DIAMOND_AXE
        - DIAMOND_HOE
        - LEATHER_HELMET
        - LEATHER_CHESTPLATE
        - LEATHER_LEGGINGS
        - LEATHER_BOOTS
        - WOOD_SWORD
        - WOOD_SPADE
        - WOOD_PICKAXE
        - WOOD_AXE
        - WOOD_HOE
        - BOW
        - ARROW
        - GOLDEN_APPLE
        - COOKED_BEEF
        - MUSHROOM_SOUP
    Herbalism:
      enabled: true
      material: DIAMOND_HOE
      name: "&6Herbalism"
      slot: 5
      title: Herbalism Item Filter
      items:
        - CARROT
        - POTATO
        - SEEDS
        - PUMPKIN_SEEDS
        - MELON_SEEDS
        - RED_MUSHROOM
        - BROWN_MUSHROOM
        - POISONOUS_POTATO
        - WHEAT
        - PUMPKIN
        - MELON
        - CACTUS
        - VINE
        - GRASS
        - SAPLING
        - HAY_BLOCK
        - YELLOW_FLOWER
        - RED_ROSE
        - WATER_LILY
    Drops:
      enabled: true
      material: BONE
      name: "&6Drops"
      slot: 6
      title: Drops Item Filter
      items:
        - BONE
        - ARROW
        - STRING
        - SULPHUR
        - ROTTEN_FLESH
        - ENDER_PEARL
        - BLAZE_ROD
        - GHAST_TEAR
        - GOLD_NUGGET
        - SPIDER_EYE
        - MAGMA_CREAM
        - PRISMARINE_SHARD
        - SLIME_BALL
        - LEATHER
        - FEATHER
        - MUTTON
        - RABBIT
        - RAW_CHICKEN
        - PORK
        - RAW_BEEF
        - INK_SACK
        - IRON_INGOT
        - SNOW_BALL
        - PRISMARINE_CRYSTALS
        - EGG